version: 2
jobs:
  verify:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn lint
      - run: yarn test
      - run: yarn coverage
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn build

workflows:
  version: 2
  one_and_two:
    jobs:
      - verify
      - build
